server:
  port: 8080

spring:
  application:
    name: auth-service

  datasource:
    url: ${DB_AUTH_URL:jdbc:postgresql://localhost:5432/auth_db}
    username: ${DB_AUTH_USERNAME:postgres}
    password: ${DB_AUTH_PASSWORD:postgres}
    hikari:
      maximum-pool-size: 10
      connection-timeout: 20000

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: validate
    open-in-view: false

  flyway:
    enabled: true
    locations: classpath:db/migration
    validate-on-migrate: true

  kafka:
    bootstrap-servers: ${KAFKA_URL:localhost:9094}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

jwt:
  secret: ${JWT_SECRET:mySecretKeyThatIsAtLeast256BitsLongForHS256}
  access:
    expiration: 900000
  refresh:
    expiration: 604800000

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus,metrics
  endpoint:
    health:
      show-details: when-authorized
  metrics:
    tags:
      application: ${spring.application.name}
  tracing:
    enabled: true
    sampling:
      probability: 1.0
    propagation:
      type: w3c
    baggage:
      enabled: false
  otlp:
    tracing:
      endpoint: ${MANAGEMENT_OTLP_TRACING_ENDPOINT:http://localhost:4318/v1/traces}

jdbc:
  datasource-proxy:
    include-parameter-values: false
    query:
      enable-logging: false
  opentelemetry:
    enabled: true
