server:
  port: 8084

spring:
  application:
    name: notification-service

  datasource:
    url: ${DB_NOTIFICATION_URL:jdbc:postgresql://localhost:5432/notifications_db}
    username: ${DB_NOTIFICATION_USERNAME:postgres}
    password: ${DB_NOTIFICATION_PASSWORD:postgres}
    hikari:
      maximum-pool-size: 5
      connection-timeout: 20000

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: validate
    open-in-view: false

  flyway:
    enabled: true
    locations: classpath:db/migration
    validate-on-migrate: true

  kafka:
    bootstrap-servers: ${KAFKA_URL:localhost:9094}
    consumer:
      group-id: notification-service-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus,metrics
  endpoint:
    health:
      show-details: when-authorized
  metrics:
    tags:
      application: ${spring.application.name}