spring:
  application:
    name: bank-service

  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/db}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: validate

  kafka:
    bootstrap-servers: ${KAFKA_URL:localhost:9094}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

jwt:
  secret: ${JWT_SECRET:mySecretKeyThatIsAtLeast256BitsLongForHS256}
  access:
    expiration: 900000
  refresh:
    expiration: 604800000

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus,metrics

  endpoint:
    health:
      show-details: always

  metrics:
    tags:
      application: ${spring.application.name}