server:
  port: 8000

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: auth-service
          uri: ${AUTH_SERVICE_URL:http://localhost:8080}
          predicates:
            - Path=/auth/**,/users/**
        - id: banking-service
          uri: ${BANKING_SERVICE_URL:http://localhost:8082}
          predicates:
            - Path=/accounts/**,/transactions/**
