name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to VPS
        uses: appleboy/ssh-action@v1.0.3

        with:
          host: ${{ vars.VPS_HOST }}
          username: ${{ vars.VPS_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}

          script: |
            cd ~/cloud-based-backend-service
            git fetch origin
            git checkout main
            git reset --hard origin/main
            docker compose up -d --build